AWSTemplateFormatVersion: 2010-09-09
Description: 'WAF Sampler'

Parameters:

  scheduleInterval:
    Type: Number
    Default: 10
    AllowedValues: [ 5, 10, 15, 20, 30 ]
    Description: 'Specify the schedule interval'

  archivePeriod:
    Type: Number
    Default: 60
    MinValue: 0
    Description: 'Specify the time after which the sampled logs will be archived to Glacier. Specify 0 to not archive to Glacier.'

  retentionPeriod:
    Type: Number
    Default: 1825
    MinValue: 0
    Description: 'Specify the time after which the sampled logs will be deleted. Specify 0 to not delete ever.'

  flattenEntries:
    Type: String
    Default: 'false'
    AllowedValues: [ 'true',  'false' ]
    Description: 'Specify if the JSON entries headers-structure should be flattened.'

  adminEmail:
    Type: String
    Default: ''
    Description: 'Specify the administrative email address that will receive notifications of failed invocations.'

Conditions:

  archiveSamples: !Not [ !Equals [ !Ref archivePeriod, 0 ] ]
  deleteSamples: !Not [ !Equals [ !Ref retentionPeriod, 0 ] ]

Resources:

# ==================================== #
# S3 Bucket
# ==================================== #

  WafSamples:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
    Properties:
      BucketName: !Sub 'waf-sampler-${AWS::AccountId}'
      AccessControl: Private
      LifecycleConfiguration:
        Rules:
          - Id: 'archive'
            Status: !If [ archiveSamples, 'Enabled', 'Disabled' ]
            Transitions:
              - StorageClass: 'GLACIER'
                TransitionInDays: !Ref archivePeriod
          - Id: 'delete'
            Status: !If [ deleteSamples, 'Enabled', 'Disabled' ]
            ExpirationInDays: !Ref retentionPeriod
      Tags:
        - Key: 'Application'
          Value: 'waf-sampler'

# ==================================== #
# Lambda stuff
# ==================================== #

  WafSamplerRole:
    Type: 'AWS::IAM::Role'
    DependsOn: WafSamples
    Properties:
      RoleName: !Sub 'waf-sampler-lambda-role-${AWS::Region}'
      Path: '/'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: 'lambda.amazonaws.com'
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
      Policies:
      - PolicyName: 'root'
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: 'Allow'
            Action:
              - 'waf:GetSampledRequests'
            Resource:
              - 'arn:aws:waf::*:rule/*'
              - 'arn:aws:waf::*:webacl/*'
          - Effect: 'Allow'
            Action:
              - 'waf:ListRules'
              - 'waf:ListWebACLs'
              - 'waf:GetWebACL'
            Resource: '*'
          - Effect: 'Allow'
            Action:
              - 's3:PutObject'
            Resource: !Sub
                        - '${s3Arn}/*'
                        - s3Arn: !GetAtt WafSamples.Arn

  WafSampler:
    Type: 'AWS::Lambda::Function'
    DependsOn: WafSamplerRole
    Properties:
      FunctionName: 'waf-sampler'
      Description: 'Function storing waf sampled requests in S3'
      Environment:
        Variables:
          interval: !Sub '${scheduleInterval}'
          bucketName: !Ref WafSamples
          flattenEntries: !Ref flattenEntries
      Runtime: 'python2.7'
      Handler: 'index.handler'
      Code:
        ZipFile: !Sub |
          import os
          import json
          import boto3
          import datetime

          # get the environment parameters
          interval = os.environ['interval']
          bucketName = os.environ['bucketName']
          flattenEntries = os.environ['flattenEntries']

          # initialize the clients
          waf = boto3.client('waf')
          bucket = boto3.resource('s3').Bucket(bucketName)

          # main handler routine
          def handler(event, context):

              # get the timestamp and determine the period
              end = getTimestamp()
              start = end - datetime.timedelta(minutes=int(interval))

              # capture the rule-ids and their corresponding names
              ruleIds = {}
              rules = waf.list_rules()
              for rule in rules['Rules']:
                  ruleIds[rule['RuleId']] = rule['Name']

              # iterate over all web acls
              acls = waf.list_web_acls()
              for acl in acls['WebACLs']:

                  # get the ACL metadata
                  webAclId = acl['WebACLId']
                  webAcl = waf.get_web_acl( WebACLId = webAclId )['WebACL']

                  # blocked will hold all blocked antries for this acl
                  blocked = []

                  # iterate over all rules
                  for rule in webAcl['Rules']:

                      # get the blocked entries
                      lines = sampleBlocked(
                                      webAclId,
                                      webAcl['Name'],
                                      rule['RuleId'],
                                      ruleIds[rule['RuleId']],
                                      start,
                                      end
                              )
                      # and append them to the 'blocked' array
                      blocked.extend(lines)

                  # debug output to CloudWatch logs
                  print('{}: {} blocked sampled requests'.format(webAclId, len(blocked)))

                  # if any blocked entries
                  if blocked:
                      # save them to S3
                      save(webAclId, start, blocked)

              return 0

          def sampleBlocked(webAclId, webAclName, ruleId, ruleName, start, end):

              samples = waf.get_sampled_requests(
                          WebAclId=webAclId,
                          RuleId=ruleId,
                          TimeWindow={
                              'StartTime': start,
                              'EndTime': end
                          },
                          MaxItems=500
                      )

              lines = []

              for sample in samples['SampledRequests']:
                  if sample['Action'] == 'BLOCK':

                      request = {
                          'timestamp': sample['Timestamp'],
                          'action': sample['Action'],
                          'web-acl-id': webAclId,
                          'web-acl-name': webAclName,
                          'rule-id': ruleId,
                          'rule-name': ruleName,
                          'client-ip': sample['Request']['ClientIP'],
                          'country': sample['Request']['Country'],
                          'method': sample['Request']['Method'],
                          'uri': sample['Request']['URI'],
                          'http-version': sample['Request']['HTTPVersion']
                      }

                      if flattenEntries == 'true':
                        for header in sample['Request']['Headers']:
                            request['header-' + header['Name'].lower()] = header['Value']
                      else:
                        request['headers'] = {}
                        for header in sample['Request']['Headers']:
                            request['headers'][header['Name'].lower()] = header['Value']

                      lines.append(json.dumps(request, default=str))

              return lines

          def getTimestamp():

              timestamp = datetime.datetime.now()
              return timestamp.replace(
                          minute = timestamp.time().minute - (timestamp.time().minute%int(interval)),
                          second = 0,
                          microsecond = 0
                          )

          def save(webAclId, timestamp, lines):

              key = 'waf/blocked/{}/sample-requests-{}.json'.format(
                              webAclId,
                              timestamp.strftime("%Y-%m-%d-%H-%M-%S")
                          )

              bucket.put_object(
                  Key=key,
                  ContentType='application/json',
                  Body='\n'.join(lines)
                  )
      Timeout: 300
      MemorySize: 128
      Role: !GetAtt WafSamplerRole.Arn
      Tags:
        - Key: 'Application'
          Value: 'waf-sampler'

  WafSamplerPermission:
    Type: 'AWS::Lambda::Permission'
    DependsOn:
      - WafSampler
      - WafSamplerSchedule
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: 'waf-sampler'
      Principal: 'events.amazonaws.com'
      SourceArn: !GetAtt WafSamplerSchedule.Arn

# ==================================== #
# Failed Invocations
# ==================================== #

  FailedInvocationTopic:
    Type: 'AWS::SNS::Topic'
    Properties:
      TopicName: 'waf-sampler-failed-invocations'
      DisplayName: 'Failed invocations of WAF Sampler'
      Subscription:
        - Protocol: 'email'
          Endpoint: !Ref adminEmail


#  FailedInvocationAlarm:
#    Type: 'AWS::CloudWatch::Alarm'
#    Properties:
#      AlarmDescription: 'Alarm for failed invocations of WAF Sampler'
#      AlarmActions:
#        - !Ref FailedInvocationTopic
#      MetricName: ''
#      Namespace: ''
#      Statistic: ''
#      Period:
#      ComparisonOperator: 'GreaterThanThreshold'

# ==================================== #
# CloudWatch
# ==================================== #

  WafSamplerSchedule:
    Type: 'AWS::Events::Rule'
    DependsOn: WafSampler
    Properties:
      Name: 'waf-sampler-schedule'
      Description: 'Scheduled event for invocation of WAF Sampler function'
      ScheduleExpression: !Sub 'rate(${scheduleInterval} minutes)'
      State: 'ENABLED'
      Targets:
        - Id: 'waf-sampler'
          Arn: !GetAtt WafSampler.Arn

  WafSamplerLogGroup:
    Type: 'AWS::Logs::LogGroup'
    Properties:
      LogGroupName: !Join [ '', [ '/aws/lambda/', !Ref WafSampler ] ]
      RetentionInDays: 1


